name: macOS GTK Build (.app + .dmg)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-14
            arch: arm64
          - runner: macos-13
            arch: x64

    runs-on: ${{ matrix.runner }}

    env:
      HOMEBREW_NO_ENV_HINTS: 1
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Brew prep (reset + doctor)
        run: |
          brew update-reset || true
          brew doctor || true

      - name: Retry helper
        id: retry
        run: |
          cat > /tmp/retry.sh <<'SH'
          #!/usr/bin/env bash
          set -e
          i=0
          until "$@"; do
            i=$((i+1))
            if [ $i -ge 3 ]; then exit 1; fi
            echo "Retry $i/3 after failure..."
            sleep 15
          done
          SH
          chmod +x /tmp/retry.sh

      - name: Install core tools
        run: |
          /tmp/retry.sh brew install pkg-config || brew reinstall pkg-config
          /tmp/retry.sh brew install dylibbundler || brew reinstall dylibbundler

      - name: Install GTK stack
        run: |
          # На x64 иногда помогает поставить базовые либы явно
          if [ "${{ matrix.arch }}" = "x64" ]; then
            /tmp/retry.sh brew install glib cairo pango harfbuzz gdk-pixbuf || true
          fi
          /tmp/retry.sh brew install json-glib
          /tmp/retry.sh brew install gtk+3
          /tmp/retry.sh brew install adwaita-icon-theme || true
          brew list --versions

      - name: Build binary with Makefile
        run: |
          make clean
          make

      - name: Bundle .app
        run: bash mac/bundle.sh

      - name: Create DMG
        run: |
          ARCH_SUFFIX="-${{ matrix.arch }}"
          bash mac/create-dmg.sh "$ARCH_SUFFIX"

      - name: Show otool (debug)
        run: |
          echo "Linked libs of binary:"
          otool -L dist/UserDoc.app/Contents/MacOS/userdoc || true

      - name: Upload artifact (.app + .dmg)
        uses: actions/upload-artifact@v4
        with:
          name: UserDoc-${{ matrix.arch }}
          path: |
            dist/UserDoc.app
            dist/UserDoc-${{ matrix.arch }}.dmg
